### ISSUE TITLE
Restart games when they are finnish in https://lichess.org/games

### ISSUE THREAD

**Issue by audriu** [ornicar/chessground#155] opened 2020-11-19 16:21 UTC
For the beginning - I would like to thank you for the job you do and the service you provide :+1: 
If it is not too difficult to implement and it makes sense for you too - could the games in https://lichess.org/games be automatically updated to new ones when they are done. It would be much more visually appealing to all have those games in constant play. Thaks!

**Comment by niklasf** [comment] 2020-11-19 22:29
Duplicate of https://github.com/ornicar/lila/issues/928.

**Closed by niklasf** 2020-11-19 22:29 UTC
